AWSTemplateFormatVersion: '2010-09-09'
Description: 'Globant Assessment'
Resources:
  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "peglrole-lambda-assessment02"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "peglpol-lambda-assessment02"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ecs:RunTask"
                  - "ecs:DescribeTasks"
                Resource: "*"
              - Effect: "Allow"
                Action: "secretsmanager:GetSecretValue"
                Resource: "*"
  LambdaApiLaunchFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: pegllmb-assessment02
      Handler: app.lambda_function.handler.lambda_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      Description: Launch API stored in a docker
      MemorySize: 128
      Environment:
        Variables:
          ECS_CLUSTER: peglecs-assessment01
          TASK_DEFINITION: pegltsk-assessment01
          SUBNETS: subnet-043df85b1be85cb0e, subnet-054c55be19102e3ba
          SECURITY_GROUPS: sg-02c620c8d4d8b6a43
      TracingConfig:
        Mode: Active
  LambdaApiLaunchLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LambdaApiLaunchFunction}"
      RetentionInDays: 7